### ISSUE TITLE
Build Failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by cc-michaelu** [EdJoPaTo/mqttui#17]
Hello, I just pulled this repo and attempted to build according to the readme.

``` Compiling pollster v0.2.4
error[E0658]: use of unstable library feature 'wake_trait'
  --> /home/michael_uman/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:19:27
   |
19 |     task::{Context, Poll, Wake, Waker},
   |                           ^^^^
   |
   = note: see issue #69912 <https://github.com/rust-lang/rust/issues/69912> for more information

error[E0658]: use of unstable library feature 'wake_trait'
   --> /home/michael_uman/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:104:5
    |
104 | /     fn wake(self: Arc<Self>) {
105 | |         self.notify();
106 | |     }
    | |_____^
    |
    = note: see issue #69912 <https://github.com/rust-lang/rust/issues/69912> for more information

error[E0658]: use of unstable library feature 'wake_trait'
   --> /home/michael_uman/.cargo/registry/src/github.com-1ecc6299db9ec823/pollster-0.2.4/src/lib.rs:103:6
    |
103 | impl Wake for Signal {
    |      ^^^^
    |
    = note: see issue #69912 <https://github.com/rust-lang/rust/issues/69912> for more information

   Compiling json v0.12.4
error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `pollster`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `mqttui v0.13.0 (/home/michael_uman/gitroot/mqttui)`, intermediate artifacts can be found at `/home/michael_uman/gitroot/mqttui/target`

Caused by:
  build failed
```

Using Ubuntu 20.04
cargo 1.46.0

**Comment by EdJoPaTo** [comment]
The dependency [pollster](https://crates.io/crates/pollster) which is failing here is only making sure to build with the stable version of rust. Sadly it doesnt even work with rustc 1.48.0 which is included with the upcoming Debian bullseye.

Personally I [install rust via rustup](https://www.rust-lang.org/tools/install) which then uses the most recent rust version.

Alternatively you can use one of the precompiled binaries from the [releases](https://github.com/EdJoPaTo/mqttui/releases).

Thanks for your time of bringing up the issue!

**Comment by cc-michaelu** [comment]
> The dependency [pollster](https://crates.io/crates/pollster) which is failing here is only making sure to build with the stable version of rust. Sadly it doesnt even work with rustc 1.48.0 which is included with the upcoming Debian bullseye.
> 
> Personally I [install rust via rustup](https://www.rust-lang.org/tools/install) which then uses the most recent rust version.
> 
> Alternatively you can use one of the precompiled binaries from the [releases](https://github.com/EdJoPaTo/mqttui/releases).
> 
> Thanks for your time of bringing up the issue!

@EdJoPaTo , thank you very much for getting back to me on this. I appreciate the support. I did eventually get it to build using the very method you suggest, removing the default rustc which is installed from the Ubuntu apt repo and getting rustup to load the latest toolset. I find mqttui useful for its intended purpose. Thank you.
